name: aplikasi_shelter_bima
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.2
  firebase_analytics: ^10.1.1
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.12
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  get: ^4.6.5
  google_sign_in: ^5.4.2
  iconify_flutter: ^0.0.5
  image_picker: ^0.8.6+1
  status_alert: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
