name: aplikasi_shelter_bima
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_sign_in: ^5.4.4
  iconify_flutter: ^0.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
