// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCuSUEkAN50s4DFoVLS4DYv7RFINWl1CY',
    appId: '1:78958614773:web:c34a11a04896398b520dbc',
    messagingSenderId: '78958614773',
    projectId: 'aplikasi-kasir-shelter-bima',
    authDomain: 'aplikasi-kasir-shelter-bima.firebaseapp.com',
    storageBucket: 'aplikasi-kasir-shelter-bima.appspot.com',
    measurementId: 'G-13K868G3RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcPXMVkS_ZytyWf4XQJXk0D37ILBh027U',
    appId: '1:78958614773:android:0f8797d3636c0411520dbc',
    messagingSenderId: '78958614773',
    projectId: 'aplikasi-kasir-shelter-bima',
    storageBucket: 'aplikasi-kasir-shelter-bima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0SxOto-FFHgRXjdB-SzF3wr1aQtGpajs',
    appId: '1:78958614773:ios:1f2fa850afcfac90520dbc',
    messagingSenderId: '78958614773',
    projectId: 'aplikasi-kasir-shelter-bima',
    storageBucket: 'aplikasi-kasir-shelter-bima.appspot.com',
    androidClientId: '78958614773-vif6ge569por9qgdepjo9rman1n8ac5b.apps.googleusercontent.com',
    iosClientId: '78958614773-2933jbig1remftg621enku1vn6imrtjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiShelterBima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0SxOto-FFHgRXjdB-SzF3wr1aQtGpajs',
    appId: '1:78958614773:ios:1f2fa850afcfac90520dbc',
    messagingSenderId: '78958614773',
    projectId: 'aplikasi-kasir-shelter-bima',
    storageBucket: 'aplikasi-kasir-shelter-bima.appspot.com',
    androidClientId: '78958614773-vif6ge569por9qgdepjo9rman1n8ac5b.apps.googleusercontent.com',
    iosClientId: '78958614773-2933jbig1remftg621enku1vn6imrtjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiShelterBima',
  );
}
